export const CommunityDB = [
  {
    id: 0,
    title: "무더운 여름철 쾌적한 실내환경을 유지하는 방법",
    date: "2022년 7월 25일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/campaigns/summer-2022/M2_CampaignPage_Module8.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "다이슨 환경제어 부문 총괄 엔지니어 에반 스티븐스(Evan Stevens)가 여름철 시원하게 실내를 유지하는 방법에 대한 팁을 소개합니다.",
  },
  {
    id: 1,
    title: "반려동물의 털과 알레르기 유발 물질의 진실",
    date: "2022년 6월 15일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/markets/korea/campaigns/pet-science/Pet_Science_Stills_Imagery.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "다이슨의 미생물학팀은 첨단 연구 시설에서 반려동물의 털과 비듬, 그리고 알레르기 유발 물질이 어떻게 우리와 우리의 주변 환경에 영향을 미치는지 매우 오랜 시간동안 연구해 왔습니다. 다이슨 미생물학 팀이 발견한 사실을 자세히 알아보세요.",
  },
  {
    id: 2,
    title: "New ‘다이슨 에어랩™ 멀티 스타일러’ 출시",
    date: "2022년 6월 8일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/products/personal-care/308c/pdp/gallery/Gallery-5-Dryer-Smooth.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "다이슨이 과도한 열 없이 더욱 쉽고 빠르게 스타일링 하도록 재탄생한 ‘다이슨 에어랩™ 멀티 스타일러’를 국내 출시했습니다.",
  },
  {
    id: 3,
    title: "",
    date: "2022년 7월 15일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/apac-newsroom/korea/gresham/JDbyOB4.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "제임스 다이슨이 다이슨 STEAM(융합교육)센터 공식 개관 및 그레샴스 학교(Gresham’s School) 연설의 날을 맞아 2022년 졸업생을 대상으로 축사 연설을 진행했습니다",
  },
  {
    id: 4,
    title:
      "제임스 다이슨 어워드 2022: 다이슨에서 젊은 인재들의 아이디어를 기다립니다.",
    date: "2022년 3월 16일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/apac-newsroom/sg-jd-award/James-Dyson-Award.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "올해로 국내에서 7회째를 맞는 국제 엔지니어링 및 디자인 공모전 제임스 다이슨 어워드가 국내 참가자를 모집합니다.",
  },
  {
    id: 5,
    title: "다이슨의 공간",
    date: "2022년 5월 10일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/apac-newsroom/sjps/new/Dyson-StJames-5.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "다이슨의 새로운 공간, 세인트 제임스 파워 스테이션을 소개합니다.",
  },
  {
    id: 6,
    title: "다이슨이 그리는 가정용 로봇의 미래, 일부를 살펴보세요",
    date: "2022년 5월 25일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image//content/dam/dyson/global-newsroom/singapore-/global-robotics/Robotics_Dyson%201.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "다이슨에서 개발 중인 가사 노동을 돕는 로봇 시제품 일부를 공개하고 전 세계 우수 로보틱스 전문가 채용에 나섰습니다",
  },
  {
    id: 7,
    title:
      "다이슨 데모 VR: 제품 개발 과정에 활용된 기술로 새로운 가상 매장을 선보입니다.",
    date: "2021년 11월 23일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/global-newsroom/united-states/features/November2021/SeanHeadshot2.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "다이슨은 VR헤드셋을 활용해 고객이 집에서 다이슨의 기술을 직접 경험하고 시연해볼 수 있는 VR 기술을 공개했습니다.",
  },
  {
    id: 8,
    title: "다이슨의 글로벌 먼지 연구 2022",
    date: "2022년 2월 7일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/apac-newsroom/newsroom-accessories-v2.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "다이슨에서는 해결 방안을 고민하기 전에 문제를 진정으로 이해하려고 합니다. 가정의 먼지도 그런 문제 중 하나입니다. 먼지는 세계의 모든 가정에 존재하지만 이에 대한 사람들의 관심은 생각보다 크지 않습니다.",
  },
  {
    id: 9,
    title: "다이슨 데모 스토어 스타필드 하남을 오픈 했습니다.",
    date: "2022년 3월 02일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/apac-newsroom/korea/demo-store/dyson3_7381.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "다이슨 코리아가 스타필드 하남에 국내 두 번째 데모 스토어 ‘다이슨 데모 스토어 스타필드 하남’을 오픈했습니다. 2021년 1월 여의도 IFC 몰에 국내 첫 데모 스토어를 오픈한지 약 1년 만입니다.",
  },
  {
    id: 10,
    title: "쿨한 여름을 위한 쿨한 헤어스타일",
    date: "2021년 4월 24일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/global-newsroom/singapore-/new-air-purification/mothers-day/556mainpage.png?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "당신의 헤어 타입에 맞는 최신 헤어스타일과 다이슨의 헤어 케어 기술을 이용하여 가정에서 스타일링하는 법을 알아보세요.",
  },
  {
    id: 11,
    title:
      "다이슨 슈퍼소닉™ 헤어드라이어의 새로운 플라이어웨이 노즐을 소개합니다.",
    date: "2021년 8월 12일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/apac-newsroom/605c/dyson-flyaway-attachment-newsroom-tile.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "다이슨은 새로운 플라이어에위 노즐을 출시했습니다. 새로운 스타일링 노즐은 집에서도 살롱에서처럼 매끄럽고 윤기 있게 마무리해 줍니다.",
  },
  {
    id: 12,
    title:
      "제임스 다이슨 어워드 2021 국제전 우승 후보작 TOP20가 발표되었습니다.",
    date: "2021년 10월 13일",
    bgimg: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/apac-newsroom/sg-jd-award/James-Dyson-Award.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=1025`,
    text: "제임스 다이슨 어워드 국제전 우승 후보작들을 만나보세요.",
  },
];

export const ProductDB = [
  {
    id: 0,
    title: "다이슨 V15 디텍트™ 컴플리트(골드/골드)",
    price: "1,290,000",
    color: {
      0: "골드",
      1: "골드",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/cord-free-vacuums/sticks/range-reset-2022/v15/pdp/irsgldirgld/dynamic-media/lifestyle/Lifestyle_V15_IRSGLDIRGLD_HEPA_SB_DblCuff.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "헤파 필터레이션이 적용된 다이슨의 강력한 무선 청소기",
      1: "레이저 슬림 플러피™ 클리너 헤드와 함께 사용 가능.",
      2: "강력한 청소 성능의 과학적 근거",
      3: "헤어 스크류 툴로 긴 머리카락과 반려동물의 털을 빠르게 청소",
    },
  },
  {
    id: 1,
    title: "다이슨 V15 디텍트™ 컴플리트(옐로/니켈)",
    price: "1,290,000",
    color: {
      0: "옐로",
      1: "니켈",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/products/floorcare/sticks/v15-detect/pdp/lifestyle/Lifestyle-SV22-CORE-LB.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "다이슨의 가장 강력하고 인텔리전트한 무선 청소기",
      1: "레이저 슬림 플러피™ 클리너 헤드와 함께 사용 가능.",
      2: "강력한 청소 성능의 과학적 근거",
      3: "헤어 스크류 툴로 긴 머리카락과 반려동물의 털을 빠르게 청소",
    },
  },
  {
    id: 2,
    title: "다이슨 V12 디텍트 슬림™ 컴플리트(골드/골드)",
    price: "1,090,000",
    color: {
      0: "골드",
      1: "골드",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/products/floorcare/sticks/v12-detected-slim/pdp/lifestyle/gold/Gold.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "다이슨의 강력하고 가벼운 무선 청소기",
      1: "레이저 슬림 플러피™ 클리너 헤드와 함께 사용 가능.",
      2: "강력한 청소 성능의 과학적 근거",
      3: "헤어 스크류 툴로 긴 머리카락과 반려동물의 털을 빠르게 청소",
    },
  },
  {
    id: 3,
    title: "다이슨 V12 디텍트 슬림™ 컴플리트(옐로/니켈)",
    price: "1,090,000",
    color: {
      0: "옐로",
      1: "니켈",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/products/floorcare/sticks/v12-detected-slim/pdp/lifestyle/yellow/Yellow.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "다이슨의 강력하고 가벼운 무선 청소기",
      1: "레이저 슬림 플러피™ 클리너 헤드와 함께 사용 가능.",
      2: "엉킴 방지 클리너 헤드 탑재",
      3: "헤어 스크류 툴로 긴 머리카락과 반려동물의 털을 빠르게 청소",
    },
  },
  {
    id: 4,
    title: "다이슨 V11 앱솔루트",
    price: "1,090,000",
    color: {},
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/markets/korea/products/floorcare/sticks/v11-2022/Lifestyle_248L_IRSNKIRCO_SB_MTB.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "집 안 구석구석을 깊숙이 청소하기 위한 설계",
      1: "강력한 파워로 깊숙한 곳의 먼지까지",
      2: "지능적인 실시간 디스플레이",
    },
  },
  {
    id: 5,
    title: "다이슨 싸이클론 V10 앱솔루트",
    price: "899,000",
    color: {},
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/newzealand/floorcare/cord-free/sticks/v10/features/nz-only-V10-Copper-Trade-Up.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "카펫과 마룻바닥 어디든 깊숙하게 청소 가능",
      1: "다이슨 V10 디지털 모터로 작동",
      2: "엉킴 방지 클리너 헤드 탑재",
    },
  },
  {
    id: 6,
    title: "다이슨 싸이클론 V10 플러피 오리진",
    price: "799,000",
    color: {},
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/lifestyle/230306-01.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "완벽한 바닥 청소하기 위한 설계",
      1: "다이슨 V10 디지털 모터로 작동",
    },
  },
  {
    id: 7,
    title: "다이슨 옴니-글라이드™ 컴플리트(골드/니켈)",
    price: "699,000",
    color: {
      0: "골드",
      1: "니켈",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/markets/singapore/products/floorcare/sticks/674-gold-tool.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "방향 조정이 쉬운 무선 청소기.",
      1: "1.9kg 가벼운 무게",
      2: "라이트 파이프 크레비스 툴 포함(어둡고 좁은 공간 청소용)",
    },
  },
  {
    id: 8,
    title: "다이슨 옴니 글라이드™ 컴플리트(퍼플/니켈)",
    price: "699,000",
    color: {
      0: "퍼플",
      1: "니켈",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/products/floorcare/handheld/omni-glide/pdp-purple/0_Lifestyle-Machine_800X388_Template_PURPLE.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "방향 조정이 쉬운 무선 청소기.",
      1: "낮은 가구 틈, 좁은 공간도 간편하게 청소.",
      2: "1.9kg 가벼운 무게",
    },
  },
  {
    id: 9,
    title: "다이슨 마이크로 1.5kg™",
    price: "699,000",
    color: {},
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/products/floorcare/sticks/547-micro/gold-variant/N547_Lifestyle-GOLD_800X388_Image.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "1.5kg 경량 설계1에 담은 다이슨의 무선 청소기 테크놀로지.",
      1: "제품 전체에 적용된 5단계 필터레이션",
    },
  },
  {
    id: 10,
    title: "다이슨 디지털 슬림™ 컴플리트",
    price: "899,000",
    color: {},
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/markets/hong-kong/floorcare/sticks/digital-slim/tuc_620Nickel.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "청소 성능은 그대로 어디서나 강력한 청소.",
      1: "1.9kg 가벼운 무게.",
      2: "지능적인 실시간 LCD 디스플레이.",
      3: "스탠딩 거치대 포함",
    },
  },
  {
    id: 11,
    title: "다이슨 디지털 슬림™",
    price: "799,000",
    color: {},
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/markets/hong-kong/floorcare/sticks/digital-slim/tuc_620Nickel.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "청소 성능은 그대로 어디서나 강력한 청소.",
      1: "1.9kg 가벼운 무게.",
      2: "지능적인 실시간 LCD 디스플레이.",
    },
  },
  {
    id: 12,
    title: "다이슨 아웃사이즈™",
    price: "1,290,000",
    color: {},
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/vacuums/sticks/248-l-j/lifestyle/lifestyle-red-outsize.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "25% 더 넓어진 클리너 헤드.",
      1: "150% 더 커진 먼지통.",
      2: "레이저 슬림 플러피™ 클리너 헤드와 함께 사용 가능.",
      3: "엉킴방지 헤어 스크류 툴",
    },
  },
  {
    id: 13,
    title: "New 다이슨 에어랩™ 멀티 스타일러 컴플리트(니켈/코퍼)",
    price: "699,000",
    color: {
      0: "니켈",
      1: "코퍼",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/personal-care/308c/lifestyle/400690-01.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "새롭게 설계된 스타일링 툴 포함",
      1: "가슴 길이보다 짧은 모발용",
      2: "다양한 모발 타입용",
      3: "양방향으로 컬과 웨이브를 만들어주는 새로운 배럴, 정교하게 모양을 잡아주는 브러시, 드라이부터 매끄러운 스타일링, 그리고 잔머리까지 감춰주는1 코안다 스무딩 드라이어 포함",
    },
  },
  {
    id: 14,
    title: "New 다이슨 에어랩™ 멀티 스타일러 컴플리트 롱(코퍼/니켈)",
    price: "699,000",
    color: {
      0: "코퍼",
      1: "니켈",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/personal-care/308c/lifestyle/395973-01.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "새롭게 설계된 스타일링 툴 포함",
      1: "가슴 길이 이상의 모발용",
      2: "다양한 모발 타입용",
      3: "양방향으로 컬과 웨이브를 만들어주는 새로운 배럴, 정교하게 모양을 잡아주는 브러시, 드라이부터 매끄러운 스타일링, 그리고 잔머리까지 감춰주는1 코안다 스무딩 드라이어 포함",
    },
  },
  {
    id: 15,
    title: "다이슨 코랄™ 프로페셔널",
    price: "599,000",
    color: {},
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/lifestyle/323008-01.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "헤어스타일리스트 전용 제품.",
      1: "정교한 스타일링. 손상은 반으로.1",
    },
  },
  {
    id: 16,
    title: "다이슨 코랄™ 스타일 스트레이트너(블랙니켈/푸시아)",
    price: "599,000",
    color: {
      0: "블랙니켈",
      1: "푸시아",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/personal-care/556/lifestyle/Magento-Dyson-Corrale-Lifestyle-Slider-Celsius.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "다양한 스타일링을 위한 설계.",
      1: "정교한 스타일링. 손상은 반으로.",
      2: "무선으로 사용.",
    },
  },
  {
    id: 17,
    title: "다이슨 코랄™ 스타일 스트레이트너(코퍼/니켈)",
    price: "599,000",
    color: {
      0: "코퍼",
      1: "니켈",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/personal-care/556/lifestyle/Dyson-Corrale-Lifestyle-copper-nickel.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "다양한 스타일링을 위한 설계.",
      1: "정교한 스타일링. 손상은 반으로.",
    },
  },
  {
    id: 18,
    title: "다이슨 코랄™ 스타일 스트레이트너(푸시아/니켈)",
    price: "599,000",
    color: {
      0: "푸시아",
      1: "니켈",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/personal-care/556/lifestyle/Dyson-Corrale-Lifestyle-fuschia-nickel.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "다양한 스타일링을 위한 설계.",
      1: "정교한 스타일링. 손상은 반으로.",
      2: "무선으로 사용.",
    },
  },
  {
    id: 19,
    title: "다이슨 슈퍼소닉™ 니켈/코퍼(보관 케이스 포함)",
    price: "529,000",
    color: {
      0: "니켈",
      1: "코퍼",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/markets/korea/products/personal-care/605e/411106-01.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "과도한 열 없이 빠른 건조.",
      1: "나만의 헤어스타일링을 위한 5가지 노즐.",
      2: "새로운 플라이어웨이 노즐 포함.",
      3: "지능형 열제어 시스템.",
      4: "강력한 다이슨 디지털 모터 V9 탑재.",
    },
  },
  {
    id: 20,
    title: "다이슨 슈퍼소닉™ 블루/코퍼(보관 케이스 포함)",
    price: "529,000",
    color: {
      0: "블루",
      1: "코퍼",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/markets/korea/products/personal-care/605e/412522-01.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "과도한 열 없이 빠른 건조.",
      1: "나만의 헤어스타일링을 위한 5가지 노즐.",
      2: "새로운 플라이어웨이 노즐 포함.",
      3: "지능형 열제어 시스템.",
      4: "강력한 다이슨 디지털 모터 V9 탑재.",
    },
  },
  {
    id: 21,
    title: "다이슨 슈퍼소닉™ 푸시아/아이언",
    price: "499,000",
    color: {
      0: "푸시아",
      1: "아이언",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/personal-care/605/lifestyle/lifestyle-iron-fuchsia-flyaway.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "과도한 열 없이 빠른 건조.",
      1: "나만의 헤어스타일링을 위한 5가지 노즐.",
      2: "새로운 플라이어웨이 노즐 포함.",
      3: "지능형 열제어 시스템.",
      4: "강력한 다이슨 디지털 모터 V9 탑재.",
    },
  },
  {
    id: 22,
    title: "다이슨 슈퍼소닉™ 블루/골드",
    price: "599,000",
    color: {
      0: "블루",
      1: "골드",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/lifestyle/312780-01.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "과도한 열 없이 빠른 건조.",
      1: "나만의 헤어스타일링을 위한 5가지 노즐.",
      2: "새로운 플라이어웨이 노즐 포함.",
      3: "지능형 열제어 시스템.",
      4: "23.75 캐럿 골드로 수작업 도금.",
      5: "‘젯소’ 레드 케이스 제공.",
    },
  },
  {
    id: 23,
    title: "다이슨 슈퍼소닉™ 니켈/코퍼",
    price: "499,000",
    color: {
      0: "니켈",
      1: "코퍼",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/products/personal-care/605c/variant-page/389923-01.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "과도한 열 없이 빠른 건조.",
      1: "나만의 헤어스타일링을 위한 5가지 노즐.",
      2: "새로운 플라이어웨이 노즐 포함.",
      3: "지능형 열제어 시스템.",
      4: "강력한 다이슨 디지털 모터 V9 탑재.",
    },
  },
  {
    id: 24,
    title: "다이슨 슈퍼소닉™ 블랙/니켈",
    price: "499,000",
    color: {
      0: "블랙",
      1: "니켈",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/personal-care/605/lifestyle/lifestyle-black-flyaway.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "과도한 열 없이 빠른 건조.",
      1: "나만의 헤어스타일링을 위한 5가지 노즐.",
      2: "새로운 플라이어웨이 노즐 포함.",
      3: "지능형 열제어 시스템.",
      4: "강력한 다이슨 디지털 모터 V9 탑재.",
    },
  },
  {
    id: 25,
    title: "다이슨 슈퍼소닉™ 푸시아/니켈",
    price: "499,000",
    color: {
      0: "푸시아",
      1: "니켈",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/personal-care/605/lifestyle/lifestyle-fuchsia-nickel.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=576`,
    desc: {
      0: "과도한 열 없이 빠른 건조.",
      1: "나만의 헤어스타일링을 위한 5가지 노즐.",
      2: "새로운 플라이어웨이 노즐 포함.",
      3: "지능형 열제어 시스템.",
      4: "강력한 다이슨 디지털 모터 V9 탑재.",
    },
  },
  {
    id: 26,
    title: "다이슨 슈퍼소닉™ 프로페셔널",
    price: "556,000",
    color: {},
    imgUrl: ``,
    desc: {
      0: "헤어 전문가를 위한 설계.",
      1: "더 강력한 자석 부착형 노즐.",
      2: "살롱을 위해 설계된 향상된 필터.",
      3: "3.3미터의 더욱 길어진 전원 케이블.",
      4: "다섯 가지 스타일링 노즐.",
      5: "새로운 플라이어웨이 노즐 포함.",
    },
  },

  // 헤어케어 완료

  {
    id: 27,
    title: "다이슨 쿨 공기청정기 (화이트/실버)",
    price: "899,000",
    color: {
      0: "화이트",
      1: "실버",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/ec/438e/lifestyle/438E_WHSIL_Lifestyle-desk-purifier.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      // 0: "공기 정화와 냉풍 기능을 하나로",
      // 1: "0.1마이크론 크기의 작은 미세먼지를 99.95% 제거합니다.",
      2: "HEPA H13 공기청정기 겸 선풍기",
      3: "공기 품질을 실시간으로 자동 감지 및 보고",
      4: "넓은 공간을 위한 방안 전체 공기 정화",
      5: "다이슨 링크 앱을 이용한 컨트롤",
    },
  },
  {
    id: 28,
    title: "다이슨 쿨 공기청정기 (블랙/니켈)",
    price: "899,000",
    color: {
      0: "블랙",
      1: "니켈",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/ec/438e/lifestyle/438E_BLKNK_Lifestyle-desk-purifier.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      //   0: "공기 정화와 냉풍 기능을 하나로",
      //   1: "0.1마이크론 크기의 작은 미세먼지를 99.95% 제거합니다.",
      2: "HEPA H13 공기청정기 겸 선풍기",
      3: "공기 품질을 실시간으로 자동 감지 및 보고",
      4: "넓은 공간을 위한 방안 전체 공기 정화",
      5: "다이슨 링크 앱을 이용한 컨트롤",
    },
  },
  {
    id: 29,
    title: "다이슨 쿨™ 선풍기 타워형 (화이트/ 실버)",
    price: "598,000",
    color: {
      0: "",
      1: "",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/lifestyle/300910-01.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "날개 없는 선풍기의 강력한 바람",
      1: "강력한 풍량.",
      2: "회전 제어.",
      3: "빠르게 회전하는 날개없이 안전하게.",
      4: "편리한 청소.",
    },
  },

  {
    id: 30,
    title: "다이슨 쿨™ 선풍기 타워형 (니켈/블랙)",
    price: "598,000",
    color: {
      0: "니켈",
      1: "블랙",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/lifestyle/300906-01.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "날개 없는 선풍기의 강력한 바람",
      1: "강력한 풍량.",
      2: "회전 제어.",
      3: "빠르게 회전하는 날개없이 안전하게.",
      4: "편리한 청소.",
    },
  },
  {
    id: 31,
    title: "다이슨 쿨 포름알데히드 공기청정기(화이트/골드)",
    price: "999,000",
    color: {
      0: "화이트",
      1: "골드",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/products/ec/438e/variants/438E_WHSGLD_Lifestyle-desk-purifier.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "HEPA H13 공기청정기 겸 선풍기",
      1: "포름알데히드 감지 및 파괴. ",
      2: "공기 품질을 실시간으로 자동 감지 및 보고",
      3: "넓은 공간을 위한 방안 전체 공기 정화",
      4: "다이슨 링크 앱을 이용한 컨트롤",
    },
  },
  {
    id: 32,
    title: "다이슨 쿨 포름알데히드 공기청정기(니켈/골드)",
    price: "999,000",
    color: {
      0: "니켈",
      1: "골드",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/products/ec/438e/variants/438E_NKSGLD_Lifestyle-desk-purifier.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "HEPA H13 공기청정기 겸 선풍기",
      1: "포름알데히드 감지 및 파괴. ",
      2: "공기 품질을 실시간으로 자동 감지 및 보고",
      3: "넓은 공간을 위한 방안 전체 공기 정화",
      4: "다이슨 링크 앱을 이용한 컨트롤",
    },
  },
  {
    id: 33,
    title: "다이슨 휴미디파이+쿨 포름알데히드 가습 공기청정기(화이트/골드)",
    price: "1,290,000",
    color: {
      0: "화이트",
      1: "골드",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/ec/358e/sco/lifestyle/lifestyle_machine_PH04_WHSGLD.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "포름알데히드 감지 및 파괴합니다",
      1: "방 안 전체를 정화하고 가습합니다",
      2: "반영구적 고체 포름알데히드 센서",
      3: "초미세먼지를 99.95% 제거합니다",
    },
  },
  {
    id: 34,
    title: "다이슨 휴미디파이+쿨 포름알데히드 가습 공기청정기(니켈/골드)",
    price: "1,290,000",
    color: {
      0: "니켈",
      1: "골드",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/lifestyle/369212-01.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "포름알데히드 감지 및 파괴합니다",
      1: "방 안 전체를 정화하고 가습합니다",
      2: "반영구적 고체 포름알데히드 센서",
      3: "초미세먼지를 99.95% 제거합니다",
    },
  },
  {
    id: 35,
    title: "다이슨 핫앤쿨 포름알데히드 공기청정기(화이트/골드)",
    price: "1,090,000",
    color: {
      0: "화이트",
      1: "골드",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/ec/527e/lifestyle/HP09_WHSGLD_Lifestyle_Machine_800X388.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "HEPA H13 공기청정기, 선풍기 겸 온풍기.",
      1: "포름알데히드 감지 및 파괴. ",
      2: "공기 품질을 실시간으로 자동 감지 및 보고.",
      3: "넓은 공간을 위한 방안 전체 공기 정화.",
      4: "다이슨 링크 앱 및 호환 가능한 음성 서비스를 이용한 컨트롤",
    },
  },
  {
    id: 36,
    title: "다이슨 핫앤쿨 포름알데히드 공기청정기(니켈/골드)",
    price: "1,090,000",
    color: {
      0: "니켈",
      1: "골드",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/dynamic-media/ec/527e/lifestyle/HP09_NKSGLD_Lifestyle_Machine_800X388.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "HEPA H13 공기청정기, 선풍기 겸 온풍기.",
      1: "포름알데히드 감지 및 파괴. ",
      2: "공기 품질을 실시간으로 자동 감지 및 보고.",
      3: "넓은 공간을 위한 방안 전체 공기 정화.",
      4: "다이슨 링크 앱 및 호환 가능한 음성 서비스를 이용한 컨트롤",
    },
  },
  //   공기청정기
  {
    id: 37,
    title: "다이슨 가습기(화이트/실버)",
    price: "659,000",
    color: {
      0: "화이트",
      1: "실버",
    },
    imgUrl: `https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/lifestyle/303124-01.jpg?$responsive$&cropPathE=tablet&fit=stretch,1&wid=310`,
    desc: {
      0: "더 건강한 실내 환경을 위한 위생적인 가습.",
      1: "다이슨 가습기는 특허받은 에어 멀티플라이어™ 기술로 미세한 수분을 분사합니다.",
    },
  },
  //   가습기
];
